openproblems-bio/website

.gitignore, config/_default/config.yaml, config/_default/menus.yaml, content/NeurIPS_docs/_index.md
This PR add links for the contribution guides
=> add links to contribution guides

layouts/partials/task_dataset.html
=> Add scrollbar to benchmarking tables

layouts/benchmarks/section.html, layouts/benchmarks/single.html
=> breadcrumbs back at bottom of datatable

CHANGELOG.md, _quarto.yml
=> Port missing metadata.

CHANGELOG.md
Missed that we had a CHANGELOG :)
=> Add dark mode to changelog

theme-dark.scss
=> Use a slightly darker background

results/task_template.css
Closes #171
(no, because it's fixing something that has not yet been released)
=> Make funkyheatmap header text white

competitions/competitions.css, competitions/neurips_2021/index.qmd, competitions/neurips_2022/index.qmd
Addresses https://github.com/openproblems-bio/website/issues/182
(no, dark mode not released yet)
=> Make competition sponsor cards white

CHANGELOG.md, _quarto.yml
Use a custom filter to determine if the link is external. The filter is very generic which makes it possible to keep the `site-url: https://openproblems.bio`
Closes #158
=> add new external link filter

results/tasks.css, styles.css, theme-dark.scss, theme-light.scss
=> Make dark task cards less dark

results/task_template.css
@rcannood thanks for pushing me on this one, it looks much better now!
Closes #182 closes #189
=> change funkyheatmap row colors

results/_blocks/_scaling_figure.qmd, results/task_template.css
Makes the raw results figure background transparent and then inverts colours.
=> Adapt raw results figure to dark mode

CHANGELOG.md
=> Move new changes to new version

results/_blocks/_summary_figure.qmd, results/task_template.css
=> Funkyheatmap dark theme

documentation/contribute/add_a_baseline.qmd, documentation/contribute/add_a_method.qmd, documentation/contribute/add_a_metric.qmd
Explicitly specify the python language parameter
Closes openproblems-bio/openproblems-v2#112
- ~[ ] Proposed changes are described in the CHANGELOG.md~ Not needed
=> explicitly specify the python parameter

.github/workflows/quarto_netlify.yml, CHANGELOG.md, README.md, _environment, _environment-evaluate_code, _include/_evaluate_code.qmd, _quarto-no_docs.yaml, documentation/contribute/add_a_baseline.qmd, documentation/contribute/add_a_dataset.qmd, documentation/contribute/add_a_method.qmd, documentation/contribute/getting_started.qmd, documentation/contribute/run_tests.qmd
For some of the pages, only render executable code when the 'evaluate_code' profile is active.
Closes #207
=> add evaluate_code render profile

documentation/contribute/add_a_metric.qmd
add the include `_evaluate_code.qmd` to add a metric file
=> add include to metric doc

CHANGELOG.md, styles.css
Remove navbar transition fix in css. It is now part of quarto
Closes #142  
=> revert navbar transition fix

CHANGELOG.md, _quarto.yml
Add `target: _blank` to external links in navbar
Closes #149 
=> add target _blank to navbar external links

CHANGELOG.md, styles.css
revert changes from quarto v1.3
Closes #234 and closes #235 
=> fix small issues with quarto v1.3

CHANGELOG.md, styles.css
set all headers to `font-weight: 500;`
Closes #242 
=> set all headers to the same font-weight

CHANGELOG.md, _redirects
Add `:splat` to redirect links to cover subdirs
Closes #241 
=> update _redirect with splat

CHANGELOG.md, documentation/create_component/run_tests.qmd, documentation/create_task/create_components.qmd, documentation/create_task/design_api.qmd
=> update documentation errors

CHANGELOG.md, events/2021-09_neurips/index.qmd
*  Add a link to the documentation for neurips 2021.
* Add "PR" to PR # in `changelog.md`
=> add documentation link

CHANGELOG.md, documentation/create_component/add_a_control.qmd, documentation/create_component/add_a_method.qmd, documentation/create_component/index.qmd, documentation/create_task/create_components.qmd, documentation/create_task/define_task.qmd, documentation/create_task/task_structure.qmd
Update v2 documentation by replacing "baseline" with "control".
Closes #247 
=> replace baseline with control

CHANGELOG.md, documentation/_figures/_fig_task_structure.qmd, documentation/_figures/_project_structure_dataflow.qmd, documentation/_figures/_project_structure_dataset_workflow.qmd, documentation/_figures/_project_structure_task_workflow.qmd, documentation/create_task/design_api.qmd, styles.css, theme-dark.scss, theme-light.scss
Add Dark/Light mode theming for Mermaid diagrams.
~Closes #xxxx~
=> Add Dark/Light mode theming for Mermaid diagrams.

CHANGELOG.md, _include/_read_api.qmd, documentation/_figures/_project_structure_dataset_workflow.qmd, documentation/_figures/_project_structure_task_workflow.qmd, documentation/create_component/add_a_dataset.qmd, documentation/create_task/create_components.qmd, documentation/create_task/define_task.qmd, documentation/create_task/design_api.qmd, documentation/create_task/select_datasets.qmd, documentation/create_task/task_structure.qmd, documentation/reference/openproblems-v2/src-datasets.qmd
* Extend the documentation on designing the task API
* Add documentation on writing the process dataset component
~Closes #xxxx~
=> update api docs

CHANGELOG.md, documentation/create_task/design_api.qmd, documentation/fundamentals/concepts.qmd, documentation/more_information/FAQ.qmd
=> Explicitly mention the __merge__ notation

CHANGELOG.md, documentation/create_task/define_task.qmd
Add a link to the task issue example 
Closes #264 
=> add link to task issue example

.github/workflows/quarto_netlify.yml, CHANGELOG.md
* Updated changelog
* Competition 2023 was accidentally already commited on main branch in 0a24c3c218eb5cc078654ce14e0ba566b7c8c947
=> add neurips 2023 competition page

CHANGELOG.md, documentation/fundamentals/requirements.qmd
Add optional step to requirements to install vs code
=> add vs code install

CHANGELOG.md, results/_include/_summary_figure.qmd
Apologies, everyone, I removed old version of `funkyheatmap-js` from npm (without thinking). So the summary figure for results is currently not showing: https://openproblems.bio/results/batch_integration_feature/
cc @rcannood
Here I restore this by updating to the new one.
=> Bring back funkyheatmapjs

CHANGELOG.md, documentation/create_component/_include/_add_dependencies.qmd, documentation/create_component/add_a_control.qmd, documentation/create_component/add_a_method.qmd, documentation/create_component/add_a_metric.qmd
reference the base image in add dependencies section of the `create_component` pages
Closes #281
=> add base image reference to doc

CHANGELOG.md, renv.lock, renv/activate.R
=> Update renv to v1.0.2 to improve processing time.

CHANGELOG.md
fix CI fail by updating submodule `OpenProblems-v2` to current main branch 
=> update openproblems repo

.renvignore, CHANGELOG.md, _redirects, documentation/create_component/_include/_add_dependencies.qmd, results/_include/_dataset_descriptions.qmd, results/_include/_method_descriptions.qmd, results/_include/_metric_descriptions.qmd
* Updated the `openproblems-v2` submodule (PR #295). This fixes a deprecation error due to an update in ruamel.yaml.
* Add redirect from `/benchmark_dataset` to `/events/2021-09_neurips/documentation/data/dataset.html` (#292, PR #295).
* Fixed minor issues in qmd files (PR #295).
=> Fix_website

results/_include/_results_table.qmd
=> fix issue with missing metrics

results/batch_integration_embed/data/dataset_info.json, results/batch_integration_feature/data/dataset_info.json, results/batch_integration_graph/data/dataset_info.json, results/cell_cell_communication_ligand_target/data/dataset_info.json, results/cell_cell_communication_source_target/data/dataset_info.json, results/denoising/data/dataset_info.json, results/dimensionality_reduction/data/dataset_info.json, results/label_projection/data/dataset_info.json, results/matching_modalities/data/dataset_info.json, results/spatial_decomposition/data/dataset_info.json
=> try aligning the v1 dataset ids with the v2 dataset ids

results/predict_modality/thumbnail.svg
* Update git submodule for openproblems-v2
* Add thumbnail to predict modality task
=> Add PM thumbnail

results/_generate_task_pages.py, results/_include/_load_data.qmd, results/_include/_summary_figure.qmd, results/batch_integration/index.qmd, results/cell_cell_communication_ligand_target/index.qmd, results/cell_cell_communication_source_target/index.qmd, results/denoising/index.qmd, results/dimensionality_reduction/index.qmd, results/label_projection/index.qmd, results/match_modalities/index.qmd, results/matching_modalities/index.qmd, results/predict_modality/index.qmd, results/spatial_decomposition/index.qmd
* Adds resource info to task view. [Example](https://feature-no-ref-add-resource-info--openproblems.netlify.app/results/batch_integration/).
=> Add resource info to task results

documentation/fundamentals/getting_started.qmd, documentation/reference/naming/index.qmd
Add the git branch naming convention documentation
=> Add git branch naming convention

CHANGELOG.md, results/_include/_summary_figure.qmd
=> update funkyheastmap to v0.2.5

CHANGELOG.md, style/styles.css
Fix tab color when not active in dark mode
Closes #229
=> Fix tab color when not active in dark mode

CHANGELOG.md
=> Update changelog with missing PR changes

CHANGELOG.md, datasets/openproblems_neurips2021/bmmc_cite/data/state.yaml, datasets/openproblems_neurips2021/bmmc_cite/index.qmd, datasets/openproblems_neurips2021/bmmc_multiome/data/state.yaml, datasets/openproblems_neurips2021/bmmc_multiome/index.qmd
Update neurips 2021 datasets pages to update categories
=> Update neurips2021 categories

CHANGELOG.md, _quarto.yml, results/_generate_task_pages.py
=> add katex math-method

CHANGELOG.md, results/_include/_summary_figure.qmd
* Fix `e is null` error. Orig: https://openproblems.bio/results/label_projection/, New: https://fix-no-ref-summary-figure--openproblems.netlify.app/results/label_projection/
=> fix null error

results/_include/_load_data.qmd, results/_include/_summary_figure.qmd
=> fix scaling

CHANGELOG.md, documentation/advanced_topics/create_a_dataset_loader.qmd, documentation/create_component/_include/_add_dependencies.qmd, documentation/create_task/dataset_processor.qmd, documentation/fundamentals/datasets.qmd
* Update documentation about base_images
* Use base images in dataset_processor file.
=> Update base images in documentation

.github/workflows/quarto_netlify.yml, documentation/advanced_topics/create_a_dataset_loader.qmd, documentation/create_task/index.qmd, documentation/reference/openproblems/test-resources.qmd
=> fix missing links

library.bib, results/foundation_models/index.qmd
=> Add references to foundation models page

results/perturbation_prediction/data/dataset_info.json, results/perturbation_prediction/data/method_info.json, results/perturbation_prediction/data/metric_execution_info.json, results/perturbation_prediction/data/metric_info.json, results/perturbation_prediction/data/quality_control.json, results/perturbation_prediction/data/results.json, results/perturbation_prediction/data/task_info.json
=> update perturbation prediction results

CHANGELOG.md, datasets/_include/_index_template.qmd, results/_include/_dataset_descriptions.qmd
* Added url to the benchmark datasets that link to the dataset page
* Add "n cells x m genes" to datasetinfo instead of "n x m"
* Fix used in links on the datasets details pages
=> Add dataset links and semantic changes

CHANGELOG.md, results/_include/_summary_figure.qmd
=> Update resource results when filtering

.github/workflows/quarto_netlify.yml, documentation/create_task/create_workflow.qmd
=> Add workflow docs

results/_include/_baseline_descriptions.qmd, results/_include/_method_descriptions.qmd, results/_include/_metric_descriptions.qmd
=> Fix for when components or datasets have more than one reference
